### ISSUE TITLE
Mark alpine-rootfs as EOL

### ISSUE THREAD

**Issue by yakushabb** [flathub/io.github.paledega.alpine-rootfs#2]
The source code repository and developer account related to alpine-rootfs seem to have been deleted.

@bbhtt Is it possible to mark the application as EOL?

https://github.com/paledega/alpine-rootfs

**Comment by bbhtt** [comment]
https://github.com/flathub/io.github.paledega.alpine-rootfs/releases/download/20221006/20221006.zip

https://github.com/flathub/io.github.paledega.alpine-rootfs/releases/download/20221006/alpine.tar.gz

Replace the url with these.
